<a href="https://colab.research.google.com/github/Surabatthinimounika9999/restaurant_sales_forecasting/blob/master/data_analysis_telecust_(4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving telecust1.csv to telecust1.csv

In [2]:
import pandas as pd
path = 'telecust1.csv'
df = pd.read_csv(path)
df.tail(5)

     region  age  marital  address  income ed  retire  gender  reside  custcat
995       3   39        0        0      27  3       0       1       3        1
996       1   34        0        2      22  5       0       1       1        1
997       3   59        0       40     944  5       0       1       1        4
998       3   49        0       18      87  2       0       1       1        3
999       3   36        1        7      39  3       0       1       3        2

In [3]:
import numpy as np

In [4]:
df.head(10)

   region  age  marital  address  income   ed  retire  gender  reside  custcat
0       2   35        1        9      64    4       0       0       2        1
1       3   23        1        7     136  NaN       0       0       6        4
2       3   52        1       24     116    1       0       1       2        3
3       2   34        0       12      33    2       0       1       1        1
4       2   30        1        9      30    1       0       0       4        3
5       2   39        0       17      78    2       0       1       1        3
6       3   23        1        2      19    2       0       1       5        2
7       2   35        0        5      76    2       0       0       3        4
8       3   59        1        7     166    ?       0       0       5        3
9       1   41        1       21      72    1       0       0       3        2

In [5]:
df['age']

0      35
1      23
2      52
3      34
4      30
       ..
995    39
996    34
997    59
998    49
999    36
Name: age, Length: 1000, dtype: int64

In [6]:
df[['address', 'ed']]

     address   ed
0          9    4
1          7  NaN
2         24    1
3         12    2
4          9    1
..       ...  ...
995        0    3
996        2    5
997       40    5
998       18    2
999        7    3

[1000 rows x 2 columns]

In [7]:
df.describe()

,region,age,marital,address,income,retire,gender,reside,custcat
count,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,2.0220,41.645000,0.495000,11.551000,77.535000,0.047000,0.517000,2.331000,2.487000
std,0.8162,12.581545,0.500225,10.086681,107.044165,0.211745,0.499961,1.435793,1.120306
min,1.0000,18.000000,0.000000,0.000000,9.000000,0.000000,0.000000,1.000000,1.000000
25%,1.0000,32.000000,0.000000,3.000000,29.000000,0.000000,0.000000,1.000000,1.000000
50%,2.0000,40.000000,0.000000,9.000000,47.000000,0.000000,1.000000,2.000000,3.000000
75%,3.0000,51.000000,1.000000,18.000000,83.000000,0.000000,1.000000,3.000000,3.000000
max,3.0000,77.000000,1.000000,55.000000,1668.000000,1.000000,1.000000,8.000000,4.000000

In [ ]:
df.isnull().sum()

region     0
age        0
marital    0
address    0
income     0
ed         1
retire     0
gender     0
reside     0
custcat    0
dtype: int64

In [ ]:
df['ed'].value_counts()

ed
2    287
4    233
3    209
1    204
5     65
?      1
Name: count, dtype: int64

In [ ]:
df.replace("?", np.nan, inplace=True)

In [ ]:
df.isnull().sum()

region     0
age        0
marital    0
address    0
income     0
ed         2
retire     0
gender     0
reside     0
custcat    0
dtype: int64

In [ ]:
df.dropna(subset=["ed"], axis=0, inplace = True)

In [ ]:
df.isnull().sum()

region     0
age        0
marital    0
address    0
income     0
ed         0
retire     0
gender     0
reside     0
custcat    0
dtype: int64

In [ ]:
df['age'].max()

77

In [ ]:
df.corr()

<ipython-input-15-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,region,age,marital,address,income,retire,gender,reside,custcat
region,1.000000,0.014484,-0.083269,0.011423,0.022158,0.006138,0.053215,-0.070921,-0.026008
age,0.014484,1.000000,-0.017808,0.660881,0.325990,0.430235,-0.007843,-0.256510,0.055720
marital,-0.083269,-0.017808,1.000000,-0.011151,-0.045443,-0.077742,0.010461,0.625304,0.082172
address,0.011423,0.660881,-0.011151,1.000000,0.227561,0.292376,0.007437,-0.200696,0.068816
income,0.022158,0.325990,-0.045443,0.227561,1.000000,-0.083391,0.040193,-0.101089,0.133608
retire,0.006138,0.430235,-0.077742,0.292376,-0.083391,1.000000,0.053506,-0.139846,0.009320
gender,0.053215,-0.007843,0.010461,0.007437,0.040193,0.053506,1.000000,0.021264,-0.003097
reside,-0.070921,-0.256510,0.625304,-0.200696,-0.101089,-0.139846,0.021264,1.000000,0.078179
custcat,-0.026008,0.055720,0.082172,0.068816,0.133608,0.009320,-0.003097,0.078179,1.000000

In [ ]:
df.dtypes

region      int64
age         int64
marital     int64
address     int64
income      int64
ed         object
retire      int64
gender      int64
reside      int64
custcat     int64
dtype: object

In [ ]:
avg = df['ed'].astype("float").mean()

In [ ]:
df.replace(np.nan, avg, inplace=True)

In [ ]:
df.isnull().sum()

region     0
age        0
marital    0
address    0
income     0
ed         0
retire     0
gender     0
reside     0
custcat    0
dtype: int64

In [ ]:
df.dtypes

region      int64
age         int64
marital     int64
address     int64
income      int64
ed         object
retire      int64
gender      int64
reside      int64
custcat     int64
dtype: object

In [ ]:
df.head()

   region  age  marital  address  income ed  retire  gender  reside  custcat
0       2   35        1        9      64  4       0       0       2        1
2       3   52        1       24     116  1       0       1       2        3
3       2   34        0       12      33  2       0       1       1        1
4       2   30        1        9      30  1       0       0       4        3
5       2   39        0       17      78  2       0       1       1        3